### ISSUE TITLE
Chat page error

### ISSUE THREAD

**Issue by mihai9112** [mihai9112/reazzon#11]
![image](https://user-images.githubusercontent.com/4330582/66110519-da44ce00-e5be-11e9-8513-a83995ef6f4f.png)

**Comment by ujwalbasnet1** [comment]
These are due to incomplete registration, when the user is not registered then '[NULL]' will be shown in his/her username place and reazzons list will be empty. And in settings page empty will be shown

**Comment by mihai9112** [comment]
Even if the registration is not complete, this should be handled by the code to either show blank space or something else. I shouldn't see an unhandled error
