### ISSUE TITLE
Getting wrong notification

### ISSUE THREAD

**Issue by mihai9112** [mihai9112/reazzon#14]
Sending a message from user2 to user1 will send the notification to user2 which is the sender. This is a bug. The receiver user1 should receive the notification
![Test3](https://user-images.githubusercontent.com/4330582/66210729-6c79ce80-e6b2-11e9-965f-38445b0b05f3.PNG)

**Comment by ujwalbasnet1** [comment]
due to push token of the same device stored in both users, its happening. And is solved in new push
