### ISSUE TITLE
running the app

### ISSUE THREAD

**Issue by kzawadi** [mihai9112/reazzon#16]
can you please give some guide on how to get the app running ..i have configured firebase and fb auth ..enabled google ..email and Facebook sign in...also google people API and the fingerprints but i can build the app not succeeded logging in...also i have seen your using the cloud functions can you share them in this repo

**Comment by mihai9112** [comment]
Hello Kzawadi, making the application to run on other devices other than my laptop was not my priority unfortunately. If you want to use the application as a guide or inspiration for your own projects, you are welcomed. If you want to contribute to the app, let me know. I'm sorry I can't support you at the moment, but if you do have any specific questions I will do my best to answer them.

**Comment by kzawadi** [comment]
Hello mihai9112,  i got you i was ... interested and curious but it is very good as a guide and inspiration and hey what does REAZZON mean.

**Comment by mihai9112** [comment]
You can see more information here: https://reazzon.com/
