### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by mihai9112** [mihai9112/reazzon#6]
E/flutter ( 6678): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The method 'hasUserName' was called on null.
E/flutter ( 6678): Receiver: null
E/flutter ( 6678): Tried calling: hasUserName()
E/flutter ( 6678): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
E/flutter ( 6678): #1      _LoginPageState.buildButton.<anonymous closure>.<anonymous closure> (package:reazzon/src/pages/login_page.dart:442:40)
E/flutter ( 6678): #2      _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter ( 6678): #3      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter ( 6678): #4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter ( 6678): #5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
E/flutter ( 6678): #6      _DelayedData.perform (dart:async/stream_impl.dart:591:14)
E/flutter ( 6678): #7      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
E/flutter ( 6678): #8      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
E/flutter ( 6678): #9      _rootRun (dart:async/zone.dart:1120:38)
E/flutter ( 6678): #10     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter ( 6678): #11     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter ( 6678): #12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter ( 6678): #13     _rootRun (dart:async/zone.dart:1124:13)
E/flutter ( 6678): #14     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter ( 6678): #15     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter ( 6678): #16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter ( 6678): #17     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter ( 6678): #18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)

**Comment by ujwalbasnet1** [comment]
Its due to some error in AppState   
Function(User) get setUser => _userController.sink.add;
must be
Function(User) get setUser => _userController.add;

its fixed.
