### ISSUE TITLE
Cannot add new events after calling close

### ISSUE THREAD

**Issue by mihai9112** [mihai9112/reazzon#7]
W/IInputConnectionWrapper( 7184): getCursorCapsMode on inactive InputConnection
I/flutter ( 7184): ChatBloc: load chat list event dispatched
E/flutter ( 7184): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Bad state: Cannot add new events after calling close
E/flutter ( 7184): #0      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:249:24)
E/flutter ( 7184): #1      Subject._add (package:rxdart/src/subjects/subject.dart:124:16)
E/flutter ( 7184): #2      Subject.add (package:rxdart/src/subjects/subject.dart:118:5)
E/flutter ( 7184): #3      new BLOCBase.<anonymous closure>.<anonymous closure> (package:reazzon/src/chat/base_bloc/base_bloc.dart:25:53)
E/flutter ( 7184): #4      _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter ( 7184): #5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter ( 7184): #6      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter ( 7184): #7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
E/flutter ( 7184): #8      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
E/flutter ( 7184): #9      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)
E/flutter ( 7184): #10     _MapStream._handleData (dart:async/stream_pipe.dart:232:10)
E/flutter ( 7184): #11     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
E/flutter ( 7184): #12     _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter ( 7184): #13     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter ( 7184): #14     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter ( 7184): #15     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
E/flutter ( 7184): #16     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
E/flutter ( 7184): #17     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)
E/flutter ( 7184): #18     _MapStream._handleData (dart:async/stream_pipe.dart:232:10)
E/flutter ( 7184): #19     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
E/flutter ( 7184): #20     _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter ( 7184): #21     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter ( 7184): #22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter ( 7184): #23     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
E/flutter ( 7184): #24     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
E/flutter ( 7184): #25     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
E/flutter ( 7184): #26     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
E/flutter ( 7184): #27     _rootRun (dart:async/zone.dart:1120:38)
E/flutter ( 7184): #28     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter ( 7184): #29     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter ( 7184): #30     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter ( 7184): #31     _rootRun (dart:async/zone.dart:1124:13)
E/flutter ( 7184): #32     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter ( 7184): #33     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter ( 7184): #34     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter ( 7184): #35     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter ( 7184): #36     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)

**Comment by ujwalbasnet1** [comment]
after what the error occurs?
