### ISSUE TITLE
Getting stream close error multiple times

### ISSUE THREAD

**Issue by mihai9112** [mihai9112/reazzon#8]
E/flutter ( 5711): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Bad state: Cannot add new events after calling close
E/flutter ( 5711): #0      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:249:24)
E/flutter ( 5711): #1      Subject._add (package:rxdart/src/subjects/subject.dart:124:16)
E/flutter ( 5711): #2      Subject.add (package:rxdart/src/subjects/subject.dart:118:5)
E/flutter ( 5711): #3      _StreamSinkWrapper.add (package:rxdart/src/subjects/subject.dart:150:13)
E/flutter ( 5711): #4      new BlocEventStateBase.<anonymous closure>.<anonymous closure> (package:reazzon/src/chat/base_bloc/base_bloc.dart:38:31)
E/flutter ( 5711): #5      Stream.forEach.<anonymous closure>.<anonymous closure> (dart:async/stream.dart:893:45)
E/flutter ( 5711): #6      _runUserCode (dart:async/stream_pipe.dart:11:23)
E/flutter ( 5711): #7      Stream.forEach.<anonymous closure> (dart:async/stream.dart:893:11)
E/flutter ( 5711): #8      _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter ( 5711): #9      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter ( 5711): #10     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter ( 5711): #11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
E/flutter ( 5711): #12     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
E/flutter ( 5711): #13     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
E/flutter ( 5711): #14     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
E/flutter ( 5711): #15     _rootRun (dart:async/zone.dart:1120:38)
E/flutter ( 5711): #16     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter ( 5711): #17     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter ( 5711): #18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter ( 5711): #19     _rootRun (dart:async/zone.dart:1124:13)
E/flutter ( 5711): #20     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter ( 5711): #21     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter ( 5711): #22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter ( 5711): #23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter ( 5711): #24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)

**Comment by ujwalbasnet1** [comment]
Pushed latest, check the issue must be resolved.
