### ISSUE TITLE
Getting rendering issues

### ISSUE THREAD

**Issue by mihai9112** [mihai9112/reazzon#9]
D/skia    ( 5711): Shader compilation error
D/skia    ( 5711): ------------------------
D/skia    ( 5711): Errors:
D/skia    ( 5711):
D/skia    ( 5711): Shader compilation error
D/skia    ( 5711): ------------------------
D/skia    ( 5711): Errors:
D/skia    ( 5711):
D/skia    ( 5711): Shader compilation error
D/skia    ( 5711): ------------------------
D/skia    ( 5711): Errors:
D/skia    ( 5711):
D/skia    ( 5711): Shader compilation error
D/skia    ( 5711): ------------------------
D/skia    ( 5711): Errors:

**Comment by ujwalbasnet1** [comment]
Please try running apps by 
1. flutter clean
2. uninstall apps in emulator or device and run
- this must solve the error

**Comment by mihai9112** [comment]
Flutter clean does not solve the issue

**Comment by ujwalbasnet1** [comment]
The error is also seen when running on device?

**Comment by mihai9112** [comment]
https://github.com/flutter/flutter/issues/33018
